### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by patrickberkeley** [suitcss/components-arrange#12]
The description of this repo says "a bit like flexbox". What were/are the reasons for not using flexbox for this component? Are there any plans/interest in either converting this component to flexbox or creating a new one that uses it?

**Comment by necolas** [comment]
> What were/are the reasons for not using flexbox for this component?

2 years ago it wasn't a realistic option. You should just use flexbox now.

**Comment by patrickberkeley** [comment]
:thumbsup: thanks for the info.
