### ISSUE TITLE
Remove vendor prefixes

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/components-arrange#15]
In `Arrange` the vendor prefixes for `box-model` were added by hand.
Autoprefixer should take care of that so we can remove them.

**Comment by giuseppeg** [comment]
Update: this is not possible right now because in suitcss/preprocessor autoprefixer is configured to support only the `last 2 Firefox/Chrome/Safari versions` while `Arrange` should work on older versions too. I guess that it is ok to keep the prefix then.

**Comment by simonsmith** [comment]
Good to keep track of this though.

**Comment by simonsmith** [comment]
I think we could just remove them as according to [caniuse](http://caniuse.com/#search=box-sizing) the older versions make up something like `0.02%`. 

In the unlikely event someone needed to support Firefox 4, they could just tweak their preprocessor config (which we didn't have at the time of this issue).

**Comment by giuseppeg** [comment]
@simonsmith :+1: thanks for fixing this ;)
