### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by simonsmith** [suitcss/components-arrange#16]
As per https://github.com/suitcss/components-arrange/issues/12#issuecomment-108932344 we now have better ways to achieve what this component offered. 

https://github.com/suitcss/utils-flex & https://github.com/suitcss/utils-size offer various flex options, and to some extent https://github.com/suitcss/components-grid/ does too.

Plus the media query scoped rules are much more useful.

**Comment by giuseppeg** [comment]
A big number of companies don't use flexbox in production yet, Arrange is a good alternative still imo.

**Comment by simonsmith** [comment]
Feels like it would be more suitable as a utility otherwise.

**Comment by giuseppeg** [comment]
I'd just keep it as-is, the activity on the repo is very low anyway :)

**Comment by simonsmith** [comment]
Okay, sounds good. It does seem a little limiting to not change layout across device size, but maybe not worth the effort for such small usage as you say :)

Shall we think about merging the proposed PRs then? Seem pretty good to me.

cc @timkelty

**Comment by timkelty** [comment]
Yep - Let's merge em in and just leave as is.
